/* Auto-generated by genmsg_cpp for file /media/sf_youbot_edinburgh/workspaces/andrew/src/cyphy-vis-slam/image_cache/srv/GetImage.srv */
#ifndef IMAGE_CACHE_SERVICE_GETIMAGE_H
#define IMAGE_CACHE_SERVICE_GETIMAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"



#include "sensor_msgs/Image.h"
#include "sensor_msgs/Image.h"
#include "sensor_msgs/Image.h"
#include "sensor_msgs/Image.h"

namespace image_cache
{
template <class ContainerAllocator>
struct GetImageRequest_ {
  typedef GetImageRequest_<ContainerAllocator> Type;

  GetImageRequest_()
  : from(0)
  , to()
  , rectified(false)
  {
  }

  GetImageRequest_(const ContainerAllocator& _alloc)
  : from(0)
  , to(_alloc)
  , rectified(false)
  {
  }

  typedef int32_t _from_type;
  int32_t from;

  typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _to_type;
  std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  to;

  typedef uint8_t _rectified_type;
  uint8_t rectified;


  typedef boost::shared_ptr< ::image_cache::GetImageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_cache::GetImageRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetImageRequest
typedef  ::image_cache::GetImageRequest_<std::allocator<void> > GetImageRequest;

typedef boost::shared_ptr< ::image_cache::GetImageRequest> GetImageRequestPtr;
typedef boost::shared_ptr< ::image_cache::GetImageRequest const> GetImageRequestConstPtr;



template <class ContainerAllocator>
struct GetImageResponse_ {
  typedef GetImageResponse_<ContainerAllocator> Type;

  GetImageResponse_()
  : from_id(0)
  , to_id()
  , from_l()
  , from_r()
  , to_l()
  , to_r()
  {
  }

  GetImageResponse_(const ContainerAllocator& _alloc)
  : from_id(0)
  , to_id(_alloc)
  , from_l(_alloc)
  , from_r(_alloc)
  , to_l(_alloc)
  , to_r(_alloc)
  {
  }

  typedef int32_t _from_id_type;
  int32_t from_id;

  typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _to_id_type;
  std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  to_id;

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _from_l_type;
   ::sensor_msgs::Image_<ContainerAllocator>  from_l;

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _from_r_type;
   ::sensor_msgs::Image_<ContainerAllocator>  from_r;

  typedef std::vector< ::sensor_msgs::Image_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::Image_<ContainerAllocator> >::other >  _to_l_type;
  std::vector< ::sensor_msgs::Image_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::Image_<ContainerAllocator> >::other >  to_l;

  typedef std::vector< ::sensor_msgs::Image_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::Image_<ContainerAllocator> >::other >  _to_r_type;
  std::vector< ::sensor_msgs::Image_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::Image_<ContainerAllocator> >::other >  to_r;


  typedef boost::shared_ptr< ::image_cache::GetImageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_cache::GetImageResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetImageResponse
typedef  ::image_cache::GetImageResponse_<std::allocator<void> > GetImageResponse;

typedef boost::shared_ptr< ::image_cache::GetImageResponse> GetImageResponsePtr;
typedef boost::shared_ptr< ::image_cache::GetImageResponse const> GetImageResponseConstPtr;


struct GetImage
{

typedef GetImageRequest Request;
typedef GetImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetImage
} // namespace image_cache

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::image_cache::GetImageRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::image_cache::GetImageRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::image_cache::GetImageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a1ec92a8ece4f3e75b4d829c9a3a2dd4";
  }

  static const char* value(const  ::image_cache::GetImageRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa1ec92a8ece4f3e7ULL;
  static const uint64_t static_value2 = 0x5b4d829c9a3a2dd4ULL;
};

template<class ContainerAllocator>
struct DataType< ::image_cache::GetImageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "image_cache/GetImageRequest";
  }

  static const char* value(const  ::image_cache::GetImageRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::image_cache::GetImageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
int32 from\n\
int32[] to\n\
bool rectified\n\
\n\
";
  }

  static const char* value(const  ::image_cache::GetImageRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::image_cache::GetImageResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::image_cache::GetImageResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::image_cache::GetImageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "715532082a0455e476f20b354f3beb2a";
  }

  static const char* value(const  ::image_cache::GetImageResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x715532082a0455e4ULL;
  static const uint64_t static_value2 = 0x76f20b354f3beb2aULL;
};

template<class ContainerAllocator>
struct DataType< ::image_cache::GetImageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "image_cache/GetImageResponse";
  }

  static const char* value(const  ::image_cache::GetImageResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::image_cache::GetImageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 from_id\n\
int32[] to_id\n\
sensor_msgs/Image from_l\n\
sensor_msgs/Image from_r\n\
sensor_msgs/Image[] to_l\n\
sensor_msgs/Image[] to_r\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::image_cache::GetImageResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::image_cache::GetImageRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.from);
    stream.next(m.to);
    stream.next(m.rectified);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetImageRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::image_cache::GetImageResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.from_id);
    stream.next(m.to_id);
    stream.next(m.from_l);
    stream.next(m.from_r);
    stream.next(m.to_l);
    stream.next(m.to_r);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetImageResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<image_cache::GetImage> {
  static const char* value() 
  {
    return "977c89c0bbd082bbbbc98818a5de36b1";
  }

  static const char* value(const image_cache::GetImage&) { return value(); } 
};

template<>
struct DataType<image_cache::GetImage> {
  static const char* value() 
  {
    return "image_cache/GetImage";
  }

  static const char* value(const image_cache::GetImage&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<image_cache::GetImageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "977c89c0bbd082bbbbc98818a5de36b1";
  }

  static const char* value(const image_cache::GetImageRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<image_cache::GetImageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "image_cache/GetImage";
  }

  static const char* value(const image_cache::GetImageRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<image_cache::GetImageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "977c89c0bbd082bbbbc98818a5de36b1";
  }

  static const char* value(const image_cache::GetImageResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<image_cache::GetImageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "image_cache/GetImage";
  }

  static const char* value(const image_cache::GetImageResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // IMAGE_CACHE_SERVICE_GETIMAGE_H

