controller_list:
  - name: fake_BaseAndArm_controller
    joints:
      - base_dummy_revolute_joint
      - base_dummy_prismatic_x_joint
      - base_dummy_prismatic_y_joint
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
  - name: fake_Gripper_controller
    joints:
      - gripper_finger_joint_l
      - gripper_finger_joint_r
  - name: fake_Arm_controller
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5