# generated from catkin/cmake/template/pkgConfig.cmake.in

# append elements to a list if they are not already in the list
# copied from catkin/cmake/list_append_unique.cmake to keep pkgConfig
# self contained
macro(_list_append_unique listname)
  foreach(_item ${ARGN})
    list(FIND ${listname} ${_item} _index)
    if(_index EQUAL -1)
      list(APPEND ${listname} ${_item})
    endif()
  endforeach()
endmacro()

# remove duplicate libraries, generalized from PCLConfig.cmake.in
macro(_remove_duplicate_libraries _unfiltered_libraries _final_filtered_libraries)
  set(_filtered_libraries)
  set(_debug_libraries)
  set(_optimized_libraries)
  set(_other_libraries)
  set(_waiting_for_debug 0)
  set(_waiting_for_optimized 0)
  set(_library_position -1)
  foreach(library ${${_unfiltered_libraries}})
    if("${library}" STREQUAL "debug")
      set(_waiting_for_debug 1)
    elseif("${library}" STREQUAL "optimized")
      set(_waiting_for_optimized 1)
    elseif(_waiting_for_debug)
      list(FIND _debug_libraries "${library}" library_position)
      if(library_position EQUAL -1)
        list(APPEND ${_filtered_libraries} debug ${library})
        list(APPEND _debug_libraries ${library})
      endif()
      set(_waiting_for_debug 0)
    elseif(_waiting_for_optimized)
      list(FIND _optimized_libraries "${library}" library_position)
      if(library_position EQUAL -1)
        list(APPEND ${_filtered_libraries} optimized ${library})
        list(APPEND _optimized_libraries ${library})
      endif()
      set(_waiting_for_optimized 0)
    else("${library}" STREQUAL "debug")
      list(FIND _other_libraries "${library}" library_position)
      if(library_position EQUAL -1)
        list(APPEND ${_filtered_libraries} ${library})
        list(APPEND _other_libraries ${library})
      endif()
    endif("${library}" STREQUAL "debug")
  endforeach(library)
  set(_final_filtered_libraries _filtered_libraries)
endmacro()


if(object_recognition_reconstruction_CONFIG_INCLUDED)
  return()
endif()
set(object_recognition_reconstruction_CONFIG_INCLUDED TRUE)

# set variables for source/devel/install prefixes
if("TRUE" STREQUAL "TRUE")
  set(object_recognition_reconstruction_SOURCE_PREFIX /home/yiming/ros_workspace/youbot/workspaces/yiming/src/object_recognition/reconstruction)
  set(object_recognition_reconstruction_DEVEL_PREFIX /home/yiming/ros_workspace/youbot/workspaces/yiming/devel)
  set(object_recognition_reconstruction_INSTALL_PREFIX "")
  set(object_recognition_reconstruction_PREFIX ${object_recognition_reconstruction_DEVEL_PREFIX})
else()
  set(object_recognition_reconstruction_SOURCE_PREFIX "")
  set(object_recognition_reconstruction_DEVEL_PREFIX "")
  set(object_recognition_reconstruction_INSTALL_PREFIX /home/yiming/ros_workspace/youbot/workspaces/yiming/install)
  set(object_recognition_reconstruction_PREFIX ${object_recognition_reconstruction_INSTALL_PREFIX})
endif()

# warn when using a deprecated package
if(NOT "" STREQUAL "")
  set(_msg "WARNING: package 'object_recognition_reconstruction' is deprecated")
  # append custom deprecation text if available
  if(NOT "" STREQUAL "TRUE")
    set(_msg "${_msg} ()")
  endif()
  message("${_msg}")
endif()

# flag project as catkin-based to distinguish if a find_package()-ed project is a catkin project
set(object_recognition_reconstruction_FOUND_CATKIN_PROJECT TRUE)

if(NOT "/opt/ros/hydro/include/opencv;/opt/ros/hydro/include;/usr/include/pcl-1.7;/usr/include/eigen3;/usr/include;/usr/include/ni;/usr/include/vtk-5.8;/usr/include/qhull" STREQUAL "")
  set(object_recognition_reconstruction_INCLUDE_DIRS "")
  set(_include_dirs "/opt/ros/hydro/include/opencv;/opt/ros/hydro/include;/usr/include/pcl-1.7;/usr/include/eigen3;/usr/include;/usr/include/ni;/usr/include/vtk-5.8;/usr/include/qhull")
  foreach(idir ${_include_dirs})
    if(IS_ABSOLUTE ${idir} AND IS_DIRECTORY ${idir})
      set(include ${idir})
    elseif("${idir}" STREQUAL "include")
      get_filename_component(include "${object_recognition_reconstruction_DIR}/../../../include" ABSOLUTE)
      if(NOT IS_DIRECTORY ${include})
        message(FATAL_ERROR "Project 'object_recognition_reconstruction' specifies '${idir}' as an include dir, which is not found.  It does not exist in '${include}'.  Ask the maintainer 'Vincent Rabaud <vincent.rabaud@gmail.com>' to fix it.")
      endif()
    else()
      message(FATAL_ERROR "Project 'object_recognition_reconstruction' specifies '${idir}' as an include dir, which is not found.  It does neither exist as an absolute directory nor in '/home/yiming/ros_workspace/youbot/workspaces/yiming/src/object_recognition/reconstruction/${idir}'.  Ask the maintainer 'Vincent Rabaud <vincent.rabaud@gmail.com>' to fix it.")
    endif()
    _list_append_unique(object_recognition_reconstruction_INCLUDE_DIRS ${include})
  endforeach()
endif()

set(libraries "/opt/ros/hydro/lib/libopencv_calib3d.so;/opt/ros/hydro/lib/libopencv_contrib.so;/opt/ros/hydro/lib/libopencv_core.so;/opt/ros/hydro/lib/libopencv_features2d.so;/opt/ros/hydro/lib/libopencv_flann.so;/opt/ros/hydro/lib/libopencv_gpu.so;/opt/ros/hydro/lib/libopencv_highgui.so;/opt/ros/hydro/lib/libopencv_imgproc.so;/opt/ros/hydro/lib/libopencv_legacy.so;/opt/ros/hydro/lib/libopencv_ml.so;/opt/ros/hydro/lib/libopencv_nonfree.so;/opt/ros/hydro/lib/libopencv_objdetect.so;/opt/ros/hydro/lib/libopencv_photo.so;/opt/ros/hydro/lib/libopencv_stitching.so;/opt/ros/hydro/lib/libopencv_superres.so;/opt/ros/hydro/lib/libopencv_video.so;/opt/ros/hydro/lib/libopencv_videostab.so;/usr/lib/libboost_system-mt.so;/usr/lib/libboost_filesystem-mt.so;/usr/lib/libboost_thread-mt.so;/usr/lib/libboost_date_time-mt.so;/usr/lib/libboost_iostreams-mt.so;/usr/lib/libboost_serialization-mt.so;/usr/lib/libpcl_common.so;/usr/lib/libflann_cpp_s.a;/usr/lib/libpcl_kdtree.so;/usr/lib/libpcl_octree.so;/usr/lib/libpcl_search.so;/usr/lib/libOpenNI.so;/usr/lib/libpcl_io.so;/usr/lib/libpcl_sample_consensus.so;/usr/lib/libpcl_filters.so;/usr/lib/libpcl_visualization.so;/usr/lib/libpcl_outofcore.so;/usr/lib/libpcl_features.so;/usr/lib/libpcl_segmentation.so;/usr/lib/libpcl_people.so;/usr/lib/libpcl_registration.so;/usr/lib/libpcl_recognition.so;/usr/lib/libpcl_keypoints.so;/usr/lib/libqhull.so;/usr/lib/libpcl_surface.so;/usr/lib/libpcl_tracking.so;/usr/lib/libpcl_apps.so;/usr/lib/libboost_system-mt.so;/usr/lib/libboost_filesystem-mt.so;/usr/lib/libboost_thread-mt.so;/usr/lib/libboost_date_time-mt.so;/usr/lib/libboost_iostreams-mt.so;/usr/lib/libboost_serialization-mt.so;/usr/lib/libqhull.so;/usr/lib/libOpenNI.so;/usr/lib/libflann_cpp_s.a")
foreach(library ${libraries})
  if(TARGET ${library})
    list(APPEND object_recognition_reconstruction_LIBRARIES ${library})
  elseif(IS_ABSOLUTE ${library})
    list(APPEND object_recognition_reconstruction_LIBRARIES ${library})
  else()
    set(lib_path "")
    set(lib "${library}-NOTFOUND")
    # since the path where the library is found is returned we have to iterate over the paths manually
    foreach(path /home/yiming/ros_workspace/youbot/workspaces/yiming/devel/lib;/home/yiming/ros_workspace/youbot/workspaces/yiming/devel/lib;/opt/ros/hydro/lib)
      find_library(lib ${library}
        PATHS ${path}
        NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
      if(lib)
        set(lib_path ${path})
        break()
      endif()
    endforeach()
    if(lib)
      _list_append_unique(object_recognition_reconstruction_LIBRARY_DIRS ${lib_path})
      list(APPEND object_recognition_reconstruction_LIBRARIES ${lib})
    else()
      # as a fall back for non-catkin libraries try to search globally
      find_library(lib ${library})
      if(NOT lib)
        message(FATAL_ERROR "Project '${PROJECT_NAME}' tried to find library '${library}'.  The library is neither a target nor built/installed properly.  Did you compile project 'object_recognition_reconstruction'?  Did you find_package() it before the subdirectory containing its code is included?")
      endif()
      list(APPEND object_recognition_reconstruction_LIBRARIES ${lib})
    endif()
  endif()
endforeach()

set(object_recognition_reconstruction_EXPORTED_TARGETS "")
# create dummy targets for exported code generation targets to make life of users easier
foreach(t ${object_recognition_reconstruction_EXPORTED_TARGETS})
  if(NOT TARGET ${t})
    add_custom_target(${t})
  endif()
endforeach()

set(depends "ecto;ecto_image_pipeline;ecto_pcl;object_recognition_core;opencv_candidate")
foreach(depend ${depends})
  string(REPLACE " " ";" depend_list ${depend})
  # the package name of the dependency must be kept in a unique variable so that it is not overwritten in recursive calls
  list(GET depend_list 0 object_recognition_reconstruction_dep)
  list(LENGTH depend_list count)
  if(${count} EQUAL 1)
    # simple dependencies must only be find_package()-ed once
    if(NOT ${object_recognition_reconstruction_dep}_FOUND)
      find_package(${object_recognition_reconstruction_dep} REQUIRED)
    endif()
  else()
    # dependencies with components must be find_package()-ed again
    list(REMOVE_AT depend_list 0)
    find_package(${object_recognition_reconstruction_dep} REQUIRED ${depend_list})
  endif()
  _list_append_unique(object_recognition_reconstruction_INCLUDE_DIRS ${${object_recognition_reconstruction_dep}_INCLUDE_DIRS})
  list(APPEND object_recognition_reconstruction_LIBRARIES ${${object_recognition_reconstruction_dep}_LIBRARIES})
  _list_append_unique(object_recognition_reconstruction_LIBRARY_DIRS ${${object_recognition_reconstruction_dep}_LIBRARY_DIRS})
  list(APPEND object_recognition_reconstruction_EXPORTED_TARGETS ${${object_recognition_reconstruction_dep}_EXPORTED_TARGETS})
endforeach()

if(object_recognition_reconstruction_LIBRARIES)
  _remove_duplicate_libraries(object_recognition_reconstruction_LIBRARIES object_recognition_reconstruction_LIBRARIES)
endif()

set(pkg_cfg_extras "")
foreach(extra ${pkg_cfg_extras})
  if(NOT IS_ABSOLUTE ${extra})
    set(extra ${object_recognition_reconstruction_DIR}/${extra})
  endif()
  include(${extra})
endforeach()
