joint_limits:
  arm_joint_3:
    has_velocity_limits: true
    max_velocity: 1.57079632679
    has_acceleration_limits: true
    max_acceleration: 0.314159265358
  arm_joint_5:
    has_velocity_limits: true
    max_velocity: 1.57079632679
    has_acceleration_limits: true
    max_acceleration: 0.314159265358
  arm_joint_2:
    has_velocity_limits: true
    max_velocity: 1.57079632679
    has_acceleration_limits: true
    max_acceleration: 0.314159265358
  arm_joint_1:
    has_velocity_limits: true
    max_velocity: 1.57079632679
    has_acceleration_limits: true
    max_acceleration: 0.314159265358
  arm_joint_4:
    has_velocity_limits: true
    max_velocity: 1.57079632679
    has_acceleration_limits: true
    max_acceleration: 0.314159265358