/* Auto-generated by genmsg_cpp for file /media/sf_youbot_edinburgh/workspaces/andrew/src/cyphy-vis-slam/slam_backend/msg/NodeAdded.msg */
#ifndef SLAM_BACKEND_MESSAGE_NODEADDED_H
#define SLAM_BACKEND_MESSAGE_NODEADDED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace slam_backend
{
template <class ContainerAllocator>
struct NodeAdded_ {
  typedef NodeAdded_<ContainerAllocator> Type;

  NodeAdded_()
  : header()
  , node_id(0)
  {
  }

  NodeAdded_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , node_id(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint32_t _node_id_type;
  uint32_t node_id;


  typedef boost::shared_ptr< ::slam_backend::NodeAdded_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slam_backend::NodeAdded_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct NodeAdded
typedef  ::slam_backend::NodeAdded_<std::allocator<void> > NodeAdded;

typedef boost::shared_ptr< ::slam_backend::NodeAdded> NodeAddedPtr;
typedef boost::shared_ptr< ::slam_backend::NodeAdded const> NodeAddedConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::slam_backend::NodeAdded_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::slam_backend::NodeAdded_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace slam_backend

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::slam_backend::NodeAdded_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::slam_backend::NodeAdded_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::slam_backend::NodeAdded_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0f0f149dcbc88289a8b92f87d91db39b";
  }

  static const char* value(const  ::slam_backend::NodeAdded_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0f0f149dcbc88289ULL;
  static const uint64_t static_value2 = 0xa8b92f87d91db39bULL;
};

template<class ContainerAllocator>
struct DataType< ::slam_backend::NodeAdded_<ContainerAllocator> > {
  static const char* value() 
  {
    return "slam_backend/NodeAdded";
  }

  static const char* value(const  ::slam_backend::NodeAdded_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::slam_backend::NodeAdded_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint32 node_id\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::slam_backend::NodeAdded_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::slam_backend::NodeAdded_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::slam_backend::NodeAdded_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::slam_backend::NodeAdded_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.node_id);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct NodeAdded_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slam_backend::NodeAdded_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::slam_backend::NodeAdded_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "node_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.node_id);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SLAM_BACKEND_MESSAGE_NODEADDED_H

