/* Auto-generated by genmsg_cpp for file /mnt/hgfs/youbot_edinburgh/workspaces/andrew/src/cyphy-vis-slam/cyphy_vslam_msgs/msg/Match.msg */
#ifndef CYPHY_VSLAM_MSGS_MESSAGE_MATCH_H
#define CYPHY_VSLAM_MSGS_MESSAGE_MATCH_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace cyphy_vslam_msgs
{
template <class ContainerAllocator>
struct Match_ {
  typedef Match_<ContainerAllocator> Type;

  Match_()
  : header()
  , fromImgSeq(0)
  , toImgSeq()
  , toImgMatch()
  {
  }

  Match_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , fromImgSeq(0)
  , toImgSeq(_alloc)
  , toImgMatch(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _fromImgSeq_type;
  int32_t fromImgSeq;

  typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _toImgSeq_type;
  std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  toImgSeq;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _toImgMatch_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  toImgMatch;


  typedef boost::shared_ptr< ::cyphy_vslam_msgs::Match_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cyphy_vslam_msgs::Match_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Match
typedef  ::cyphy_vslam_msgs::Match_<std::allocator<void> > Match;

typedef boost::shared_ptr< ::cyphy_vslam_msgs::Match> MatchPtr;
typedef boost::shared_ptr< ::cyphy_vslam_msgs::Match const> MatchConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cyphy_vslam_msgs::Match_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cyphy_vslam_msgs::Match_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cyphy_vslam_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cyphy_vslam_msgs::Match_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cyphy_vslam_msgs::Match_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cyphy_vslam_msgs::Match_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ba3cfc4913b84354e8ec41dc24ba0836";
  }

  static const char* value(const  ::cyphy_vslam_msgs::Match_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xba3cfc4913b84354ULL;
  static const uint64_t static_value2 = 0xe8ec41dc24ba0836ULL;
};

template<class ContainerAllocator>
struct DataType< ::cyphy_vslam_msgs::Match_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cyphy_vslam_msgs/Match";
  }

  static const char* value(const  ::cyphy_vslam_msgs::Match_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cyphy_vslam_msgs::Match_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32 fromImgSeq\n\
int32[] toImgSeq\n\
float64[] toImgMatch\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::cyphy_vslam_msgs::Match_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::cyphy_vslam_msgs::Match_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::cyphy_vslam_msgs::Match_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cyphy_vslam_msgs::Match_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.fromImgSeq);
    stream.next(m.toImgSeq);
    stream.next(m.toImgMatch);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Match_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cyphy_vslam_msgs::Match_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cyphy_vslam_msgs::Match_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "fromImgSeq: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fromImgSeq);
    s << indent << "toImgSeq[]" << std::endl;
    for (size_t i = 0; i < v.toImgSeq.size(); ++i)
    {
      s << indent << "  toImgSeq[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.toImgSeq[i]);
    }
    s << indent << "toImgMatch[]" << std::endl;
    for (size_t i = 0; i < v.toImgMatch.size(); ++i)
    {
      s << indent << "  toImgMatch[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.toImgMatch[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // CYPHY_VSLAM_MSGS_MESSAGE_MATCH_H

