ArmAndBase:
  kinematics_solver: IPABWeightedIKPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
Gripper:
  kinematics_solver: IPABWeightedIKPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3