controller_list:
  - name: /arm_1/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
  - name: /arm_1/gripper_controller
    action_ns: gripper_command
    type: GripperCommand
    default: true 
    joints:
      - gripper_finger_joint_l
      - gripper_finger_joint_r
  - name: /arm_2/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_2_joint_1
      - arm_2_joint_2
      - arm_2_joint_3
      - arm_2_joint_4
      - arm_2_joint_5
  - name: /arm_2/gripper_controller
    action_ns: gripper_command
    type: GripperCommand
    default: true 
    joints:
      - gripper_2_finger_joint_l
      - gripper_2_finger_joint_r
