arm_custom:
  kinematics_solver: youbot_kinematics/YoubotArmKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5
  kinematics_solver_attempts: 3
arm_joints_1:
  kinematics_solver: youbot_kinematics/YoubotArmKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
arm_joints:
  kinematics_solver: youbot_kinematics/YoubotArmKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
