arm:
  kinematics_solver: youbot_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver_attempts: 5
  kinematics_solver_search_resolution: 0.01
  kinematics_solver_timeout: 0.01
left_arm_kdl:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
