"""autogenerated by genpy from slam_backend/AddLoopClosure.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import genpy
import std_msgs.msg

class AddLoopClosure(genpy.Message):
  _md5sum = "d376227da7717c769b6aec116b010f98"
  _type = "slam_backend/AddLoopClosure"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
int32 node_id1
int32 node_id2
time interpolated_time
float32 frac
geometry_msgs/PoseWithCovarianceStamped transform

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/PoseWithCovarianceStamped
# This expresses an estimated pose with a reference coordinate frame and timestamp

Header header
PoseWithCovariance pose

================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  __slots__ = ['header','node_id1','node_id2','interpolated_time','frac','transform']
  _slot_types = ['std_msgs/Header','int32','int32','time','float32','geometry_msgs/PoseWithCovarianceStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,node_id1,node_id2,interpolated_time,frac,transform

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AddLoopClosure, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.node_id1 is None:
        self.node_id1 = 0
      if self.node_id2 is None:
        self.node_id2 = 0
      if self.interpolated_time is None:
        self.interpolated_time = genpy.Time()
      if self.frac is None:
        self.frac = 0.
      if self.transform is None:
        self.transform = geometry_msgs.msg.PoseWithCovarianceStamped()
    else:
      self.header = std_msgs.msg.Header()
      self.node_id1 = 0
      self.node_id2 = 0
      self.interpolated_time = genpy.Time()
      self.frac = 0.
      self.transform = geometry_msgs.msg.PoseWithCovarianceStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2i2If3I.pack(_x.node_id1, _x.node_id2, _x.interpolated_time.secs, _x.interpolated_time.nsecs, _x.frac, _x.transform.header.seq, _x.transform.header.stamp.secs, _x.transform.header.stamp.nsecs))
      _x = self.transform.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.transform.pose.pose.position.x, _x.transform.pose.pose.position.y, _x.transform.pose.pose.position.z, _x.transform.pose.pose.orientation.x, _x.transform.pose.pose.orientation.y, _x.transform.pose.pose.orientation.z, _x.transform.pose.pose.orientation.w))
      buff.write(_struct_36d.pack(*self.transform.pose.covariance))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.interpolated_time is None:
        self.interpolated_time = genpy.Time()
      if self.transform is None:
        self.transform = geometry_msgs.msg.PoseWithCovarianceStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.node_id1, _x.node_id2, _x.interpolated_time.secs, _x.interpolated_time.nsecs, _x.frac, _x.transform.header.seq, _x.transform.header.stamp.secs, _x.transform.header.stamp.nsecs,) = _struct_2i2If3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.transform.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.transform.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.transform.pose.pose.position.x, _x.transform.pose.pose.position.y, _x.transform.pose.pose.position.z, _x.transform.pose.pose.orientation.x, _x.transform.pose.pose.orientation.y, _x.transform.pose.pose.orientation.z, _x.transform.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.transform.pose.covariance = _struct_36d.unpack(str[start:end])
      self.interpolated_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2i2If3I.pack(_x.node_id1, _x.node_id2, _x.interpolated_time.secs, _x.interpolated_time.nsecs, _x.frac, _x.transform.header.seq, _x.transform.header.stamp.secs, _x.transform.header.stamp.nsecs))
      _x = self.transform.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.transform.pose.pose.position.x, _x.transform.pose.pose.position.y, _x.transform.pose.pose.position.z, _x.transform.pose.pose.orientation.x, _x.transform.pose.pose.orientation.y, _x.transform.pose.pose.orientation.z, _x.transform.pose.pose.orientation.w))
      buff.write(self.transform.pose.covariance.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.interpolated_time is None:
        self.interpolated_time = genpy.Time()
      if self.transform is None:
        self.transform = geometry_msgs.msg.PoseWithCovarianceStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.node_id1, _x.node_id2, _x.interpolated_time.secs, _x.interpolated_time.nsecs, _x.frac, _x.transform.header.seq, _x.transform.header.stamp.secs, _x.transform.header.stamp.nsecs,) = _struct_2i2If3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.transform.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.transform.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.transform.pose.pose.position.x, _x.transform.pose.pose.position.y, _x.transform.pose.pose.position.z, _x.transform.pose.pose.orientation.x, _x.transform.pose.pose.orientation.y, _x.transform.pose.pose.orientation.z, _x.transform.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.transform.pose.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      self.interpolated_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2i2If3I = struct.Struct("<2i2If3I")
_struct_3I = struct.Struct("<3I")
_struct_7d = struct.Struct("<7d")
_struct_36d = struct.Struct("<36d")
